### ISSUE TITLE
accent and dead key support

### ISSUE THREAD

**Issue by PaulEcoffet** [ErgoDox-EZ/fusion#12]
Keyboard layouts like french [bépo](http://bepo.fr) layout uses a lot of accented letters and dead key such as é, è, and ^, ¨ to make letters like ê, î, ï. These key are not available in fusion. Will these key be available somehow ?

Thank you for your help.

**Comment by tdegrunt** [comment]
Everything supported by the QMK firmware should be (at some point) supported by fusion. So these things will indeed be supported. Mind you that fusion is (for now) an unfinished product.
