### ISSUE TITLE
Annotate the json

### ISSUE THREAD

**Issue by lalomartins** [ErgoDox-EZ/fusion#13]
For the benefit of those wanting to edit the output by hand, it would be nice to have some clues of what's what. Like, “row 1 key 3 left side”.

JSON doesn't allow comments, but there's no reason we couldn't use an extra field for that, maybe “location”, which would then be ignored by reactor.

Bonus: if this field(s) is(are) written in a somewhat strict format, it/they can be used to generate keymap images.

**Comment by lalomartins** [comment]
Note, this is less a feature request than an RFC for something I'm thinking of doing :smile_cat:

**Comment by tdegrunt** [comment]
Have you looked at https://github.com/ErgoDox-EZ/reactor ? We're pretty close to a working version, just need to tie a few loose ends. One of them: saving layouts in the database.

**Comment by tdegrunt** [comment]
Ah. Yeah we might need position indeed, but JavaScript should keep array elements in order.

**Comment by lalomartins** [comment]
Absolutely :smiley_cat: getting fusion to run was the easiest part (I even reported an issue, but it seems the root cause is here).

What I'm looking into atm is alternative workflows, which could be especially useful as things are still in development. Like, making it easy to edit the json by hand in a text editor (this ticket), giving reactor a CLI so it can generate c from json, hex from either c or json, without messing with web requests, and who knows, maybe running the whole thing locally in a GUI container like Elektron.

Since the keyboards are shipped (and I'm typing this comment in one), I figure this would give intermediate-level users a better interim tool to hack. Intermediate as in “I know how to edit json and get around the command line but I don't want to learn a C/macro API just to customize my keyboard”.

**Comment by lalomartins** [comment]
Order is how I got around so far (edited by hand mostly because I couldn't work out how to get my json back into fusion for GUI editing), I can compare the first layer in which I know the keys, then “ok the key I want to assign is 6 after the I”. But that's way too cumbersome.

**Comment by tdegrunt** [comment]
Indeed, it's useful so have, I'm going to call it position though.

**Comment by lalomartins** [comment]
makes sense to me too.

**Comment by tdegrunt** [comment]
https://github.com/ErgoDox-EZ/fusion-rails/commit/17d47d37cf615ef997ec8bc44583d7f14ad95757
