### ISSUE TITLE
Import the layout

### ISSUE THREAD

**Issue by sethherr** [ErgoDox-EZ/fusion#14]
How can I import the layout/styles from http://rocketcode.nl/fusion/ ? It looks better there.

**Comment by tdegrunt** [comment]
Sorry for the late response (had a hand surgery, still in pain). The old code uses a little more bootstrap stuff. It hasn't had my priority really. I did add the titlebar/navbar back.

For the react/javascript code it means we just need to add some `className="btn"` code here and there.

Other styles used on that site are a bit outdated, we now support 12 different labels in the CSS, I still need to add those to the rails-models and json output.
